### ISSUE TITLE
test for jsdoc

### ISSUE THREAD

**Issue by fergald** [jackbsteinberg/get-originals-rewriter#75] opened 2019-09-10 08:27 UTC
I can't find any tests that ensure that JSDoc type annotations work e.g.

```js
/**
 * param {Element} arg
 */
function f(arg) {
    arg.scrollIntoView();
}
```

and actually that is not rewritten at all - I can't tell if that's because I've got the JSDoc wrong or the rewriter is not working.

**Comment by domenic** [comment] 2019-09-10 15:31
Dupe of https://github.com/jackbsteinberg/get-originals-rewriter/issues/31

**Closed by domenic** 2019-09-10 15:31 UTC
